from building import *

# The set of source files associated with this SConscript file.
src = Glob('src/*.c')

cwd = GetCurrentDir()
CPPPATH = [cwd + "/include"]

if GetDepend('RT_USING_DFS_DEVONLY'):
    SrcRemove(src, cwd + '/src/dfs_fs.c')

group = DefineGroup('Filesystem', src, depend = ['RT_USING_DFS'], CPPPATH = CPPPATH)

if GetDepend('RT_USING_DFS'):
    # search in the file system implementation
    list = os.listdir(cwd)
    
    for item in list:
        if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
            group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
